export const challengeDraftSeeds = [
  {
    id: 'new-holiday', title: 'Invent a new holiday', eyebrow: 'Save this one for December.',
    prompt: 'Create a brand-new holiday and an interactive way for everyone to celebrate it.',
    brief: 'Show us what the holiday celebrates, when it happens, and one delightfully specific tradition. Visitors should get to join the fun.',
    starterIdeas: ['International Pajama Parade', 'Talk Like a Sandwich Day', 'The Festival of Tiny Victories'],
    tools: ['Scratch', 'Canva Code', 'HTML + JS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'alien-planet', title: 'Build a page for an alien planet', eyebrow: 'Visitors from Earth are welcome.',
    prompt: 'Create an interactive page that introduces us to a planet nobody on Earth has visited.',
    brief: 'Show us the landscape, weather, creatures, food, or rules of life there. Give visitors at least one thing to explore or change.',
    starterIdeas: ['A planet made of pillows', 'Two suns and noodle rain', 'A travel guide for nervous astronauts'],
    tools: ['Scratch', 'Canva Code', 'HTML + CSS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'invent-a-creature', title: 'Invent a creature', eyebrow: 'Odd talents encouraged.',
    prompt: 'Invent a creature with a home, a personality, and one very surprising talent.',
    brief: 'Introduce us through a game, interactive profile, animation, or tiny world. Let visitors do something that reveals who the creature is.',
    starterIdeas: ['A shy cloud dragon', 'A sock-eating moon mouse', 'A jellyfish who tells jokes'],
    tools: ['Scratch', 'p5.js', 'Replit', 'Anything you love'], status: 'idea',
  },
  {
    id: 'tiny-theme-park', title: 'Build the world’s smallest theme park', eyebrow: 'Big thrills. Very little land.',
    prompt: 'Design a miniature theme park with at least three attractions visitors can try.',
    brief: 'Give the park a theme, a map or menu, and interactions that make each ride or attraction feel different.',
    starterIdeas: ['A park for ants', 'Breakfast-food roller coasters', 'One-room outer-space park'],
    tools: ['Scratch', 'HTML + CSS', 'Canva Code', 'Anything you love'], status: 'idea',
  },
  {
    id: 'rescue-a-snack', title: 'Rescue a snack', eyebrow: 'A tiny snack. An enormous quest.',
    prompt: 'Build an adventure where a snack is lost, trapped, or in urgent need of a hero.',
    brief: 'Create a problem, a journey, and a satisfying rescue. Give visitors at least one choice or challenge that changes what happens.',
    starterIdeas: ['Save the last space taco', 'A cupcake stuck in a volcano', 'The great runaway noodle'],
    tools: ['Scratch', 'Twine', 'HTML + JS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'create-a-snack', title: 'Create a new snack', eyebrow: 'The kitchen has no rules today.',
    prompt: 'Invent a snack that has never existed and build an interactive way to make, name, or taste-test it.',
    brief: 'Choose surprising ingredients, show what happens when they combine, and give your snack a personality, package, power, or very dramatic review.',
    starterIdeas: ['Build-your-own moon crackers', 'A mood-changing smoothie', 'The world’s crunchiest cloud'],
    tools: ['Scratch', 'Canva Code', 'HTML + JS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'mixed-up-map', title: 'Create a mixed-up map', eyebrow: 'Wrong turns strongly encouraged.',
    prompt: 'Draw an impossible map and make its strangest places explorable.',
    brief: 'Create at least three locations and a way to travel between them. Hide a shortcut, surprise, or very unhelpful landmark somewhere on the journey.',
    starterIdeas: ['A map inside a giant shoe', 'Cloud islands connected by noodles', 'A neighborhood for monsters'],
    tools: ['Scratch', 'Twine', 'HTML + CSS', 'Anything you love'], status: 'idea',
  },
] as const
