export const challengeDraftSeeds = [
  {
    id: 'chain-reaction', title: 'Make a chain reaction', eyebrow: 'One tiny tap. Total delightful chaos.',
    prompt: 'Build a world where one small action sets off a surprising chain of events.',
    brief: 'Let visitors start the action, then watch at least three connected things happen. The chain can be clever, silly, useful, or completely impossible.',
    starterIdeas: ['Dominoes that make breakfast', 'A robot wake-up sequence', 'A machine that manufactures rainbows'],
    tools: ['Scratch', 'HTML + JS', 'p5.js', 'Anything you love'], status: 'scheduled',
  },
  {
    id: 'tiny-museum', title: 'Build a tiny museum', eyebrow: 'Every exhibit has a secret.',
    prompt: 'Create a museum with at least three strange exhibits visitors can explore.',
    brief: 'Give each object something to reveal when it is tapped, clicked, or questioned. Your museum can celebrate real discoveries or things that could never exist.',
    starterIdeas: ['The museum of lost socks', 'Famous snacks through history', 'Artifacts from the year 3000'],
    tools: ['Scratch', 'Canva Code', 'HTML + CSS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'creature-translator', title: 'Invent a creature translator', eyebrow: 'Beep. Squawk. Translation, please.',
    prompt: 'Build a translator that helps humans understand an imaginary creature.',
    brief: 'Let visitors choose a sound, symbol, mood, or phrase and discover what the creature really means. Add a few translations nobody expects.',
    starterIdeas: ['Dragon sneeze dictionary', 'What houseplants say at night', 'Robot feelings decoder'],
    tools: ['Scratch', 'HTML + JS', 'Replit', 'Anything you love'], status: 'idea',
  },
  {
    id: 'mixed-up-map', title: 'Create a mixed-up map', eyebrow: 'Wrong turns strongly encouraged.',
    prompt: 'Draw an impossible map and make its strangest places explorable.',
    brief: 'Create at least three locations and a way to travel between them. Hide a shortcut, surprise, or very unhelpful landmark somewhere on the journey.',
    starterIdeas: ['A map inside a giant shoe', 'Cloud islands connected by noodles', 'A neighborhood for monsters'],
    tools: ['Scratch', 'Twine', 'HTML + CSS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'new-holiday', title: 'Invent a new holiday', eyebrow: 'You make the rules and traditions.',
    prompt: 'Create a brand-new holiday and an interactive way for everyone to celebrate it.',
    brief: 'Show us what the holiday celebrates, what people do, and one delightfully specific tradition. Visitors should get to join the fun.',
    starterIdeas: ['International Pajama Parade', 'Talk Like a Sandwich Day', 'The Festival of Tiny Victories'],
    tools: ['Scratch', 'Canva Code', 'HTML + JS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'dream-machine', title: 'Build a dream machine', eyebrow: 'Pick the ingredients. Enter the dream.',
    prompt: 'Make a machine that combines unusual ingredients into a one-of-a-kind dream.',
    brief: 'Let visitors choose two or more dream ingredients, then reveal the place, character, story, or surprise their choices create.',
    starterIdeas: ['Moonlight + pancakes', 'Dinosaurs + ballet', 'Underwater library + jetpacks'],
    tools: ['Scratch', 'HTML + JS', 'p5.js', 'Anything you love'], status: 'idea',
  },
  {
    id: 'living-shadow', title: 'Make a shadow come alive', eyebrow: 'It has plans of its own.',
    prompt: 'Create a shadow that moves, changes, or surprises us when we interact with it.',
    brief: 'Give the shadow a personality and at least two reactions. It might copy its owner, disobey completely, or lead us somewhere unexpected.',
    starterIdeas: ['A shadow that wants a pet', 'The world’s worst copycat', 'A shadow detective'],
    tools: ['Scratch', 'p5.js', 'HTML + CSS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'rescue-the-snack', title: 'Rescue a ridiculous snack', eyebrow: 'A tiny snack. An enormous quest.',
    prompt: 'Build an adventure where a snack is lost, trapped, or in urgent need of a hero.',
    brief: 'Create a problem, a journey, and a satisfying rescue. Give visitors at least one choice or challenge that changes what happens.',
    starterIdeas: ['Save the last space taco', 'A cupcake stuck in a volcano', 'The great runaway noodle'],
    tools: ['Scratch', 'Twine', 'HTML + JS', 'Anything you love'], status: 'idea',
  },
  {
    id: 'wrong-button', title: 'Make the wrong button', eyebrow: 'It never does what the label says.',
    prompt: 'Build a button that causes a different surprising result every time someone presses it.',
    brief: 'Use labels, colors, animation, sound, or story to play with expectations. Include at least three outcomes and keep every surprise friendly.',
    starterIdeas: ['Do not press the potato button', 'A button that changes gravity', 'The extremely dramatic light switch'],
    tools: ['Scratch', 'HTML + JS', 'Replit', 'Anything you love'], status: 'idea',
  },
  {
    id: 'tiny-theme-park', title: 'Build the world’s smallest theme park', eyebrow: 'Big thrills. Very little land.',
    prompt: 'Design a miniature theme park with at least three attractions visitors can try.',
    brief: 'Give the park a theme, a map or menu, and interactions that make each ride or attraction feel different.',
    starterIdeas: ['A park for ants', 'Breakfast food roller coasters', 'One-room outer-space park'],
    tools: ['Scratch', 'HTML + CSS', 'Canva Code', 'Anything you love'], status: 'idea',
  },
] as const
